### ISSUE TITLE
Int last tab ,when the web view scroll to bottom ,there is no bounces effect ,how can i add it ?

### ISSUE THREAD

**Issue by zhaozhongke** [maxep/MXParallaxHeader#3]
Nice library !

**Comment by JannyKul** [comment]
It appears as though I am having the same issue. I have created a (completely blank) UITableView with the MXParallaxHeader library and when you reach the bottom of the UITableView it sort of gets "stuck" i.e. won't let you swipe any lower to get the "bouncing" effect. I had a little tinker in the MXScrollView library and the scrollViewDidScroll delegate method still gets called whilst swiping but some part of the code must be overwriting the "bounce" at the bottom. The UITableView must be stationary at the bottom of the last cell in order to reproduce, if you swipe down a tiny bit and then up it lets the scrollView "bounce".

**Comment by tamoyal** [comment]
Anyone come up with a workaround for this? You can also see this happening in the demo so it's def a bug

**Comment by trungnguyen1791** [comment]
Did any of you guys have solutions for this? @tamoyal @JannyKul

**Comment by briannadoubt** [comment]
I had this issue when adding the parallax header from the storyboard with the parallax_header/scroll_view segues (see the falcon example in demos). 

When I switched to inserting the header with code (i.e. tableview.parallaxHeader.view = [UIView]) in viewDidLoad it fixed the issue. Not a solution but a temporary workaround at least. The only thing is that the scroll indicator does not adjust underneath the header view with this technique

**Comment by trungnguyen1791** [comment]
@bornbrie That's interesting. But I didn't see the different between there two when setting up header view.

**Comment by briannadoubt** [comment]
I ended up using this in viewDidLoad:
```
private func setParallaxHeader() {
        tableView.parallaxHeader.delegate = self
        
        tableView.parallaxHeader.view = headerView
        tableView.parallaxHeader.height = 300
        tableView.parallaxHeader.minimumHeight = 20
        
        tableView.parallaxHeader.mode = MXParallaxHeaderMode.fill
    }
```
Plus creating an `@IBOutlet var headerView: UIView!` and linking it to a UIView at the ViewController level in my storyboard.

**Comment by internalG** [comment]
@maxep Any plan to fix the bounce issue? I still see it in the latest code sample.

**Comment by sarthakappinventiv1** [comment]
@maxep How to fix this issue?
